### ISSUE TITLE
BE: mypage 기능

### ISSUE THREAD

**Issue by 5witchkr** [codestates-project-027/main-project#64]
### Todo
1. [x]  나의 운동시설 등록 및 삭제
2. [x] 나의 운동시설 출석체크 및 조회기능
3. [x] 미라클스코어 추가 및 조회기능

### Expected duration
2d

**Comment by 5witchkr** [comment]
완
